### PR TITLE
Use ensure_packages to simpify packages management

### PR DESCRIPTION
**Pull request by smortex**
~~Each one of these classes included `bacula::virtual` which in turn included both classes. As a consequence, any node declaring either a `bacula::director` or a `bacula::storage` implicitly declares the other class. This did not allowed to follow strictly the Role & Profiles pattern (see https://github.com/xaque208/puppet-bacula/issues/121#issuecomment-401885030) where you would like to use resource-style declaration for both classes.~~

Thanks to stdlib's ensure_packages (available from stdlib 3.2.0, released in 2012) we can avoid the virtual resources.

This was tested successfully on FreeBSD and Debian.

~~Known side effects:~~

* ~~Users have to include / declare both `bacula::director` and `bacula::storage` in their configuration (this is a breaking change I guess… The README suggests to use resource-style declaration of both classes, but this setup was not working so users may have used trial-and-error to find a working setup where only one of these classes is explicitly present, and the other one was incidentally included);~~
* ~~The `Class[Bacula::Storage]` is now reported correctly by PuppetDB (for some undetermined reason, I could not query PuppetDB for this class when it was included, and this change fix the problem… likely a problem in PuppetDB itself).~~

### CODE REVIEW

**Comment by xaque208** [comment]
Thanks for the PR.  This change looks good, though I'm not sure why the `Class[Bacula::Storage]` didn't show up in PuppetDB.  I'm pretty sure, though not currently looking at it, that I have bacula storage boxes that are not also bacula directors.  Looking at the `bacula::virtual` class here, it doesn't look to include either the `bacula::storage` or the `bacula::director`.

That said, this seems like a good change, and one that would be less confusing perhaps.  Does the EPP in the package name still work for the director?

**Comment by smortex** [comment]
Wow! I should be on drugs… I was so sure about what I wrote in my comments that I did not re-checked the removed code and indeed, the commit message is just madness :flushed: 

/me is looking into this to understand what the hell is going on…

**Comment by xaque208** [comment]
Hehe, don't worry. :)  Let me know if you still want this in.  I think its a fine change, but I suspect that understanding what is happening would be good regardless.

**Comment by smortex** [comment]
Well… I found nothing out of the ordinary.  I rephrased the commit message to remove the nonsense and updated the issue accordingly.

I guess the simplification worth it, so ready for review / merging.

Thanks!

**Pull request merged**
