### PR TITLE
SSL revamp

### PR DESCRIPTION
**Pull request by smortex**
Issue #70 suggests SSL key and certificate management could be extracted from the module, as it was done for PKI settings (#103).

This PR attempts to achieve this goal.

Test plan:
- [X] Allow setting each [TLS configuration directives](http://www.bacula.org/5.1.x-manuals/en/main/main/Bacula_TLS_Communications.html)
- [x] Validate changes in production
- [x] Update documentation

### CODE REVIEW

**Comment by xaque208** [comment]
Oh wonderful.  @smortex You are great.

**Comment by smortex** [comment]
:-)  However, expect this to be stale for a while: I am blocked by slow backups for a customer I would prefer not interrupt… then, I will be able to try to configure multiple backup networks through a single puppet master, which is my ultimate goal.

**Comment by smortex** [comment]
Bacula on FreeBSD does not start when unexpected configuration directives are found…  I also merged together related partials (templates).

**Comment by smortex** [comment]
We are almost there!

@xaque208 I though that using the project's wiki would make sense in order to avoid a too long README.md.  I created a few pages, including [TLS Setup](https://github.com/xaque208/puppet-bacula/wiki/TLS-Setup) that explains how to use the module with the changes of this PR.  I guess it would also make proofreading easier 😉 

If you are okay with this, I will add references to these pages in the related sections of README.md.

**Comment by xaque208** [comment]
Ah great!  The README was getting a bit long in the tooth as it was.  Thanks for thinking out of the box.

**Comment by smortex** [comment]
Excellent!  I'll update the README during the week-end!

**Comment by smortex** [comment]
I pushed an updated README.md.  The rendered result can be seen here:
https://github.com/opus-codium/puppet-bacula/tree/ssl-revamp

**Comment by smortex** [comment]
D'oh, I just realized I forgot to rebase my changes on top of `master`… I was wondering why concurrent jobs where not working *again* and realized this code was branched before e330e9f5f00bb994a686ad5aeefaed85ca2fd276 fixed the problem 😄 .

Feel free to squash the commits when merging if you want.

**Comment by xaque208** [comment]
Thanks @smortex.  I'll try to have a re-read of this again this week.

**Comment by xaque208** [comment]
Great work @smortex!  Thank you for the contribution.  I'm now running this code in my environment.

**Comment by jflorian** [comment]
@smortex Just wanted to say thanks for this (and the other recent) awesome contributions.  Gave me a bit of upgrade churn (5.2.1->5.4.0), but all for the better.

**Pull request merged**
