### PR TITLE
SSL defaults to false, but ssl.pp is included in various manifest fil…

### PR DESCRIPTION
**Pull request by ianssoftcom**
…es.  Leave only the include in common.pp and remove the others.

### CODE REVIEW

**Comment by xaque208** [comment]
Just to be clear, are you looking to deploy bacula using this module without SSL?  I ask because, while I recognize the bug, I'm also thinking that there is a case for requiring SSL in this module and not make it tune-able.  That would reduce the noise that dancing around the SSL would bring.  Thoughts?

**Comment by ianssoftcom** [comment]
In my case, as a second step I am using SSL - but my initial work with the module I was just trying to get it working as simply as possible (and that was without SSL).

**Comment by xaque208** [comment]
@ianssoftcom Were you able to get this module deployed?  Apologies for the silence.  Just looking over it again, I am still unclear that this is the correct change.  In either case, the current conditionals check for `$ssl`, but that doesn't exist as a param on any of the classes attempting to use that variable for logic switching.  I would recommend trying the module with SSL and see what issues you have.  It has been working quite well for me, but I'd like to know if there are troubles getting it going elsewhere.

**Comment by ianssoftcom** [comment]
`$ssl` is defined based on hiera in `params.pp`

`$ssl = hiera('bacula::params::ssl', false)`

and is inherited by other classes.  It was only during the early days of testing where I was testing without the added complexity of SSL.  I was able to configure with SSL without issue.

**Comment by xaque208** [comment]
@ianssoftcom Glad to hear you got SSL working.  With that in mind, do you think this PR is still valuable?  I'm inclined to think we should turn that default `false` into a `true` and cut a release reflecting that change.

**Comment by ianssoftcom** [comment]
Yes that will be fine.  If you really want to configure without ssl, you probably know what you're doing.  :-)

**Comment by xaque208** [comment]
Great, thank you for the feedback @ianssoftcom.  I hope my slowness here didn't cause you trouble.  I'm going to close this one out and I'll put a card on my board to follow up on ssl tuning.

**Pull request closed without merging**
