### PR TITLE
Distinguish nodes name and address

### PR DESCRIPTION
**Pull request by smortex**
At $WORK, we want to backup a bunch of systems managed by Puppet using this module.  Each machine has a `$::fqdn` different from it's `$trusted['certname']`. To add insults to injury, none of them is reliably resolvable, and this is *desired and unlikely to change*.

For these reasons, we need to customize the *Address* setting for [clients](https://github.com/xaque208/puppet-bacula/blob/eccfd5f13a51c2b3d900eeda483fd912d1bda14d/templates/bacula-dir-client.erb#L2..L3) and [storage](https://github.com/xaque208/puppet-bacula/blob/eccfd5f13a51c2b3d900eeda483fd912d1bda14d/templates/bacula-dir-storage.erb#L2..L3) in the director's configuration, which are currently hardcoded as *Name* without suffix.

While we are actively working on this, our changes may introduce some side effects that we would prefer discussing ASAP in order to avoid major refactoring when our patch is ready to be merged.
 
- [x] *Name* would default to `$trusted['certname']` + suffix (to be in sync with #91).  Basically, nodes are identified by their "certname";
- [x] *Address* would default to `$facts['fqdn']`. Basically, nodes are reachable by their "fqdn";
- [x] *Address* would be settable from the `bacula::client` and `bacula::storage` classes with an `address` parameter.

Example:

```puppet
class { 'bacula::client':
  client  => 'fancyname',
  address => '10.0.0.42',
}
```

@xaque208, may I ask you to check what is acceptable in the previous list so that we can discuss the rest in this issue while we work on this topic?

Thanks!

### CODE REVIEW

**Comment by xaque208** [comment]
Apologies for the delay here.  I've been preoccupied with $work myself.  

I think what you've proposed looks reasonable, and probably should have been done long ago.  Its been a matter of convenience that fqdn has been the certname for all my deployments of this module, but as you mention, that isn't necessarily the case everywhere.  For the reasons you've described, having a sane default to the resolvable hostname assumed to be the certname, with an overridable address makes some sense.

Bonus points for tests. :)

**Comment by smortex** [comment]
Cool!  I rebased the branch and added a few commits to finish this work.

Please note that for the `$trusted` variable to be usable in `rspec-puppet`, I had to switch to the master branch from the project's git repository: [support has been added but not released yet](https://github.com/rodjek/rspec-puppet/commit/79149532aa1e89097739aed7b3d8560b3f2ad945).

**Comment by xaque208** [comment]
This looks good to me.  Have you had a chance to run it in your environment?

**Comment by smortex** [comment]
We are running our [wip](https://github.com/xaque208/puppet-bacula/compare/master...opus-codium:wip) branch which includes these changes and [encryption support](https://github.com/xaque208/puppet-bacula/compare/master...opus-codium:pki) for which we have not opened a Pull Request yet.

**Comment by xaque208** [comment]
Thank you for the contribution!

**Pull request merged**
