### PR TITLE
Support for RHEL and some minor fixes

### PR DESCRIPTION
**Pull request by ManfredP**
Thank's for the great module. I had to change some things to get it to work in our environment, which is RHEL based. I also added hiera to the spec tests, so future parser is now happy.

### CODE REVIEW

**Comment by xaque208** [comment]
Great!  Have you had a chance to test this out?  Does it work?

**Comment by ManfredP** [comment]
Yes, but the tests I did were only done by running puppet apply, so no exported resources and therefore no complete function tests. In fact I only tested the package installation and checked if everything ends up in the right directory.

I tested it on RHEL6 and RHEL7 with the packages provided by RedHat. RHEL5 has no RedHat provided bacula packages, but the client works also by using the EPEL packages. I have not testet this on any Fedora, but I checked the repositories to find out, when Fedora switched to the new package names and also added it to the condition which distinguishes between the old and the new names.

I'm looking forward to deploy this module in a real puppet environment and have some backup jobs running by the end of the week.

**Comment by xaque208** [comment]
Good enough for me.  Merged this, and if you run into issues getting it deployed to prod, send more PRs please.

**Comment by ManfredP** [comment]
Thanks. For sure I'll send you another PR if there are still some issues on RHEL.

**Pull request merged**
