### PR TITLE
Switch ERB to EPP templates, improve parameters validation

### PR DESCRIPTION
**Pull request by smortex**
This PR replace ERB templates with EPP ones, enabling better parameters validation.  This switch helped fixing a few inconsistencies, and spot a few more problems which are not addressed in the PR in order to keep it short (I plan to work on these latter and open PR when appropriate).

### CODE REVIEW

**Comment by xaque208** [comment]
Oh my.  Give me a little time to come back to this.

**Comment by jflorian** [comment]
Tried this (xaque208 master with this PR merged) on my own setup to see what would happen.  Applied successfully -- win!  Minimal changes -- looks promising.

I see a `job.conf` would be changed where it has two `RunScript` blocks.  In both cases, `FailJobOnError = yes`, `RunsOnSuccess = yes`, `RunsOnFailure = no` and `RunsOnClient = no` are removed.  Looking at the docs, all of these except `RunsOnClient = no` match the default.  So, I get that explicitly setting what amounts to a default is needless noise.  WRT `RunsOnClient`, the docs say the default is `yes` and I'm not setting this value, so that reveals to me that this module previously had the default wrong (and that I now need to explicitly set this to `no` since these jobs are to be run on the Director).  It would be to mention this fix in the `CHANGELOG.md`.

The only other change I saw was related to `Messages` going to the directory instead of the syslog, which I recall seeing mentioned elsewhere, so I'm ignoring those. Thus it looks good to me in use and a significant improvement in the code quality.

@smortex Thanks for all the effort!

**Comment by smortex** [comment]
Good corner-case.  I added a commit that should fix your issue. Can you please test and report success / failure?

**Comment by jflorian** [comment]
Works perfectly now.  I'm all for merging this PR.  :+1:

**Comment by xaque208** [comment]
Excellent work.  Thanks for the PR @smortex.

**Pull request merged**
