### PR TITLE
Allow to set own bacula password

### PR DESCRIPTION
**Pull request by peceka**
Allow to set own bacula password in hiera files.

### CODE REVIEW

**Comment by xaque208** [comment]
This change isn't necessary.  Just set `bacula::client::password` in hiera and you'll override the default.

**Comment by peceka** [comment]
It doesn't work, there is no reference to this parameter from hiera:

➜  ~  git clone https://github.com/xaque208/puppet-bacula.git
Cloning into 'puppet-bacula'...
remote: Counting objects: 28866, done.
remote: Total 28866 (delta 0), reused 0 (delta 0), pack-reused 28866
Receiving objects: 100% (28866/28866), 3.56 MiB | 631.00 KiB/s, done.
Resolving deltas: 100% (14794/14794), done.
Checking connectivity... done.
➜  ~  cd puppet-bacula
➜  puppet-bacula git:(master) grep -R "bacula::client::password" *
➜  puppet-bacula git:(master)

**Comment by xaque208** [comment]
It won't show up in full because its not used anywhere.  What setting `bacula::client::password` in hiera does, is set the `password` variable on the `bacula::client` class, which you can see is present and available for setting.

Have a look here and let me know if its not clear.

https://ask.puppetlabs.com/question/117/how-can-i-use-data-bindings-in-puppet-3/

**Comment by peceka** [comment]
Ok, i will check it tomorrow then. If it work i will be so supprised. :)
And of course happy to learn smth new!

**Comment by peceka** [comment]
Of couse it works! Thanks.

**Pull request closed without merging**
