### PR TITLE
Two feature enhancements and three small fixes

### PR DESCRIPTION
**Pull request by ManfredP**
Hi,
this module work's now great on my RHEL servers, but there were 3 minor issues I fixed:
+ `Ctype` and `Collate` of the database was set to `UTF-8`, the bacula database create script sets it to `C`. I'm not a database expert, but I think `C` makes more sense with `SQL_ASCII` encoding.
+ There was a missing dependency in one file resource in the storage class.
+ The `RestoreFile` job had the `Default` schedule and failed every night.

I also added two features:
+ I have to use fileset options like `wild` multiple times, so I added support for arrays as values of the options hash.
+ I need two restore jobs with different output directories, one for the usual file restore while the os is running, and one fore bare metal recovery. So I made `Where` configurable in the job type. I also did this for `Messages` because after changing `Where` it was the last static parameter in the template.

I testet all of these changes in my environment and found no issues. I also did compatibility tests to make sure existing installations will have no problems with this changes.

### CODE REVIEW

**Comment by ManfredP** [comment]
I just discovered that the new job option for `Messages` will only work for restore jobs. I will send a new request, when I have a solution for this.

**Comment by ManfredP** [comment]
The `messages` option is now fixed, I also added some more parameters to `bacula::job`.

**Comment by xaque208** [comment]
This all looks good.  Thank you for the contribution.

**Comment by ManfredP** [comment]
Thank you for merging this.

**Pull request merged**
