### PR TITLE
Improvements for Messages

### PR DESCRIPTION
**Pull request by jflorian**
Here's a bug fix and an enhancement.  The commit messages have the details.  I will note that what I did for the Director's Messages should probably be extended to those for the Client and Storage, but I didn't need any customization there so I left them alone.  If this were done, Define[bacula::messages] should be documented as private since there would no longer be any need to use it directly.

### CODE REVIEW

**Comment by xaque208** [comment]
Thank you for the PR.

Since we're making the call to hiera here from `params.pp` for the same namespace, and its only used on the director, I think this data default is well suited to be relocated into the `data/common.yaml` under a key like `bacula::director::messages`.  If this were done, the default value on the `bacula::director` class for the `messages` param could be left off, and hiera would pick it up.  This is the approach I'd like this module to start moving in, and I started that work, but never came back to finish it up.  We don't have to do it now, but if you're willing, I think that would be an improvement on this PR.

**Comment by jflorian** [comment]
Great idea!  I'd meant to explore that more but got distracted.  I'm relatively new to data-in-modules, but fully agree that's a much cleaner approach.  Thanks for the clear pointers -- worked like a charm on the first go.

**Comment by jflorian** [comment]
Any idea why the checks fail now?  The code works in production for me.

**Comment by xaque208** [comment]
I think its because the lookup feature we're trying to use was introduced in puppet 4.3.  The tests are failing on puppet 4.2 only.  I'll drop puppet 4.2 support for this change in #83 and merge here once #83 is merged.

**Comment by xaque208** [comment]
Thank you for the contribution.  Puppet 4.2 has been dropped from the testing to support this change.

**Pull request merged**
